name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (curl, wget, libssl1.1)
      run: |
        apt-get update
        apt-get install curl wget libssl1.1 -y 
        
    ## UPDATED: SonarScanner requires Java 17+. Embold will also work fine with this.
    - name: Install Java for Embold & SonarScanner
      run: |
        apt-get install openjdk-17-jre -y 
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    ## NEW: Install the SonarScanner .NET global tool
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
        
    ## NEW: Start SonarScanner (Hook into build)
    - name: SonarScanner Begin
      run: dotnet sonarscanner begin /k:"${{ vars.SONAR_PROJECT_KEY }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ vars.SONAR_HOST_URL }}"
      
    ## NEW: Build the project (Required for Sonar analysis)
    - name: Build Project
      run: dotnet build # Add your .sln or .csproj path here if it's not in the root directory
      
    ## NEW: End SonarScanner (Upload analysis to Sonar server)
    - name: SonarScanner End
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Often needed by Sonar for PR decoration
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Embold Analyse
      run: |
        curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
        tar xvf browserstack-codequality-scanner-archive.tar.gz
        echo "Download and extract BrowserStack CQ Scanner done"
        curl --silent --location --request GET "${{ vars.EMBOLD_URL_CS }}/api/v1/repositories/443663290271da4407b0f6b857494178/scans/config/download" --header "Authorization:Bearer ${{ secrets.EMBOLD_TOKEN_CS}}" -o repository-configuration.json
        echo "Download repository configuration file done"
        ./browserstack-codequality-scanner/bin/embold-scanner analyse -u ${{ vars.EMBOLD_URL_CS }} -t ${{ secrets.EMBOLD_TOKEN_CS}} -r 443663290271da4407b0f6b857494178 -b . -d ./embold-data -c ./repository-configuration.json -v
        
    - name: Archive logs and binaries
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: parsed_files
        path: embold-data/**/*.txt
